from graphics import circle, rectangle
r=int(input("Enter the radius of circle:"))
circle.areac(r)
circle.peric(r)
l=int(input("\n Enter the length of rectangle:"))
b=int(input("\n Enter the breadth of rectangle:"))
rectangle.arear(l,b)
rectangle.perir(l,b)
from graphics.dgraphics import cuboid,sphere
l1=int(input("\n Enter the length of cuboid"))
b1=int(input("\n Enter the breadth of cuboid:"))
h1=int(input("\n Enter the height of rectangle:"))
cuboid.areacub(l1,b1,h1)
cuboid.pericub(l1,b1,h1)
r1=int(input("\n Enter the radius of sphere:"))
sphere.areas(r)
sphere.peris(r)